#!/bin/bash
# alias gp="git pull"
# aliase are temporary and valid for the current session
# to keep the aliase bespoke for each user , they should be added in 
# vim ~/.bash_profile
# add the aliaises on seperate line at the end of the last line on the page
# these alises will be bespoke for the user logged-in